### ISSUE TITLE
open file fail

### ISSUE THREAD

**Issue by ksahlin** [yuansliu/bfMEM#2]
Hi again,

I get this:

```
ksahlin@rackham:~/prefix/source/bfMEM$ ./bfmem -l 14 -k 12 -r refs_sequences.fa -q reads_batch_0.fa -o  test_bfMEM.txt
Reference file is: refs_sequences.fa
Query file is: reads_batch_0.fa
Minimum length of matches L = 14
Strands is forward
Reading Query genome ...
Time of read Query MultiFasta = 2.14279
Time of ntHashIteratorSimple = 9.02756
Reading Reference genome ...
Time of read Reference MultiFasta = 2.05288
Time of finding regions on Reference = 48.686
Time of indexing = 15.0043
Time of matches = 77.1831
open file fail!
open file fail!
open file fail!
open file fail!
open file fail!
open file fail!
Segmentation fault
```

Best,
Kristoffer

**Comment by yuansliu** [comment]
Hi Kristoffer,

In my program, it opens many files. 
Could you please try the following cmd ```ulimit -SHn 65535``` before running the bfmem?

Best,
Yuansheng

**Comment by ksahlin** [comment]
Unfortunately, I don't seem to have that command on the server :/

**Comment by ksahlin** [comment]
Ok thanks! it still seg faults somewhere. Maybe I'm pushing the -l and -k parameters below what it is designed for?

```
Minimum length of matches L = 14
Strands is forward
Reading Query genome ...
Time of read Query MultiFasta = 0.536784
Time of ntHashIteratorSimple = 8.93857
Reading Reference genome ...
Time of read Reference MultiFasta = 0.695768
Time of finding regions on Reference = 49.5163
Time of indexing = 14.6853
Time of matches = 76.688
Segmentation fault
```

I also tried `-l 20 -k 16` and `-l 24 -k 20` and it segfaults in seemingly the same place in the algorithm.

**Comment by yuansliu** [comment]
I can sure that the error "open file fail!" is caused by opening large number of files.

Could you please share the two files?

Thank you.

**Comment by ksahlin** [comment]
I'll get you the sequences soon! I'm looking into if there is a smaller offending instance that I can send.

Another question, is there a parameter to choose how many cores bfmem will use? I would like to control it to use only one core as I'm parallelizing code myself. Currently, I see that it takes up about ten cores (or the cpu usage at least says 1000% on the server).

Thank you,
K

**Comment by ksahlin** [comment]
[test_files.tar.gz](https://github.com/yuansliu/bfMEM/files/4832083/test_files.tar.gz)

Attached are test_ref and test_reads the smallest instance I could find that leads to segfault.

The command I ran was:

`time ./bfmem -l 14 -k 12 -r test_ref.fa -q test_read.fa -o  test_bfMEM.mems`

**Comment by yuansliu** [comment]
Thank you very much.

I will debug it ASAP.

**Comment by yuansliu** [comment]
```
-t  	number of threads (default t=10)
```
The above can be used to set he number of threads.

```
./bfmem -l 14 -k 12 -r test_ref.fa -q test_read.fa -o test_bfMEM.mems -t 1
```

**Comment by ksahlin** [comment]
Oh, of course. I looked at the documentation (in a rush) and didn't see it. thx!

**Comment by yuansliu** [comment]
Hi Kristoffer,

Sorry for the delay.

Fixed.

Tkx again.

Best,
Yuansheng

**Comment by ksahlin** [comment]
Hi Yuansheng,

Sorry for the slow answer. But isn't there a bug in the software if no MEMs are generated for this data for this parameter combination? Certainly, there are strings of length 14 that are identical between the queries and refs. Does the MEMs also have to be unique in order for your program to output the MEMs?

**Comment by yuansliu** [comment]
Dear Kristoffer,

I did not check the update. Sorry for it. 
I have checked the result compared with E-MEM. When k = 16, the result is the same as the E-MEM's. However, when k = 14, a bug is in my program. I will fix it.

**Comment by yuansliu** [comment]
Hi @ksahlin 

Please clone the latest version. The bug is caused by the file name. I have fixed it and have verified the result.

Thank you very much.

Best Regards,
Yuansheng
